---
title: "1. First insights"
output: html_notebook
---


```{r}
path <- "/Users/mehdi/Documents/Dev/github/sia"
df <-  read.csv(file.path(path, "./inst/analysis/score_2018-2019.csv"), sep = ";", dec = ",")
#df <- df[-(1:64), ] # trop de données manquantes sur les premiers mois
df
```


```{r}
# simple imputation
na_ids <- which(is.na(df$telespectateurs))
df$telespectateurs[na_ids] <- (df$telespectateurs[na_ids-1] + df$telespectateurs[na_ids+1])/2

ts_aud <- ts(df$telespectateurs, frequency = 5)
ts_aud.dec <- decompose(ts_aud, type = "multiplicative")
plot(ts_aud.dec)
```


```{r}
print(quantile(na.omit(ts_aud.dec$random), 1:3/4))
hist(ts_aud.dec$random)
```

-> ok !



# Score 2018-2019

```{r}
path <- "/Users/mehdi/Documents/Dev/github/sia"
df <-  read.csv(file.path(path, "./inst/analysis/score_jour_2018-2019.csv"), sep = ";", dec = ",")
na_indices <- which(is.na(df$pdm))
#print(paste("Number of na's:", length(na_indices)))
#print(paste("Percentage of missing values:", length(na_indices)/nrow(df)*100, "%"))
#if (length(na_indices)/nrow(df) > 0.05)
#  stop("Too many missing values.")
#df[na_indices, "pdm"] <- (df[na_indices - 1, "pdm"] + df[na_indices + 1, "pdm"])/2
df <- df[!is.na(df$pdm), ]
df$date <- as.character(as.Date(df$date, "%d/%m/%Y"))
df
```


```{r}
# simple imputation
var <- "pdm"
ts_aud <- ts(df[, var], frequency = 5)
ts_aud.dec <- decompose(ts_aud, type = "multiplicative")
plot(ts_aud.dec)
```


```{r}
print(quantile(na.omit(ts_aud.dec$random), 1:3/4))
hist(ts_aud.dec$random)
```






```{r}
library(plotly)

plot_ly(df, x = ~date, y = ~pdm, type="scatter")


```


```{r}
df_arch <- read.csv(file.path(path, "./inst/analysis/arches.csv"), sep = ";")
start_col <- ncol(df_arch)
for (level in levels(df_arch$arche_a)){
  df_arch[ , paste("a -", level)] <- (df_arch$arche_a == level) * 1
}
for (level in levels(df_arch$arche_b)){
  df_arch[ , paste("b -", level)] <- (df_arch$arche_b == level) * 1
}
for (level in levels(df_arch$arche_c)){
  df_arch[ , paste("c -", level)] <- (df_arch$arche_c == level) * 1
}
for (level in levels(df_arch$arche_d)){
  df_arch[ , paste("d -", level)] <- (df_arch$arche_d == level) * 1
}
col_arch <- colnames(df_arch)[(start_col):ncol(df_arch)]
df_arch <- df_arch[, c("day_first", "day_last", col_arch)]
df_arch$day_first <- as.Date(df_arch$day_first, "%d/%m/%Y")
df_arch$day_last <- as.Date(df_arch$day_last, "%d/%m/%Y")
df_arch
```



```{r}
rows <- seq.Date(df_arch$day_first[1], tail(df_arch, 1)$day_last, by = 1)
exclude <- which(weekdays(rows) %in% c("Saturday", "Sunday"))
rows <- as.character(rows[-exclude])
df_arch2 <- data.frame(row.names = rows)
for (i in colnames(df_arch)){
  df_arch2[, i] <- df_arch[1, i]
}
for (j in rownames(df_arch)){
  day_first <- df_arch[j, "day_first"]
  day_last <- df_arch[j, "day_last"]
  df_arch2[as.character(seq.Date(day_first, day_last, 1)), ] <- df_arch[j, ]
}
df_arch2
```


```{r}
df_arch3 <- df_arch2
df_arch3$date <- row.names(df_arch2)
df_merged <- merge(df, df_arch3, all.y = TRUE, all.x = FALSE, by = "date")
df_merged
```


```{r}

df_merged <- df_merged[!is.na(df_merged$pdm_trend), ]

MIN <- min(df_merged$pdm, na.rm = T)
MAX <- max(df_merged$pdm, na.rm = T)

col_names <- colnames(df_merged)

# récupération des arches
df_arches <- df_merged[, (which(col_names == "evenements") + 1):length(col_names)]
col_names <- colnames(df_arches)

# récupération des colonnes pour chaque arches
arch_names <- list()
arch_names[[1]] <- col_names[which(unlist(lapply(strsplit(colnames(df_arches), " - "), function(el){el[1] == "a"})))]
arch_names[[2]] <- col_names[which(unlist(lapply(strsplit(colnames(df_arches), " - "), function(el){el[1] == "b"})))]
arch_names[[3]] <- col_names[which(unlist(lapply(strsplit(colnames(df_arches), " - "), function(el){el[1] == "c"})))]
arch_names[[4]] <- col_names[which(unlist(lapply(strsplit(colnames(df_arches), " - "), function(el){el[1] == "d"})))]

# définition de l'échelle de couleurs
my_colors <- rev(c("#fde725", "#b5da3f", "#6fcd59", "#40b775", "#219e88", "#29828d", "#33678c", "#3f4987", "#472976", "#440154"))

# récupération des dates pour les formes
count <- 0
arch_dim <- lapply(1:4, function(i){
  matrix(unlist(lapply(arch_names[[i]], function(j){
    count <<- count + 1 
    arch_activation_period <- df_merged[which(df_merged[, j] == 1), "date"]
    c(min(arch_activation_period), max(arch_activation_period), my_colors[count %% length(my_colors) + 1])
    })), 
    nrow = 3, 
    ncol = length(arch_names[[i]]), 
    dimnames = list(c("min", "max", "col"), 
                    1:length(arch_names[[i]]) ))
})


shapes <- unlist(lapply(1:4, function(i){
  lapply(arch_names[[i]], function(j){
    
    count <<- count + 1 
    arch_activation_period <- df_merged[which(df_merged[, j] == 1), "date"]
    c(min(arch_activation_period), max(arch_activation_period), my_colors[count %% length(my_colors) + 1])
    shape_color <- my_colors[count %% length(my_colors) + 1]
    list(type = "rect", text="okok",
         fillcolor = shape_color, line = list(color = shape_color), opacity = 0.3,
         x0 = min(arch_activation_period), x1 = max(arch_activation_period), xref = "x",
         y0 = (4-i)/4 * (MAX - MIN) + MIN, y1 = (4-i+1)/4 * (MAX - MIN) + MIN, yref = "y")
  })
}), recursive = F)

p <- plot_ly(df_merged, x = ~date, y = ~pdm, type = "scatter", mode = "lines") %>%
  layout(
    title = "PDM & Arche",
    xaxis = list(title="Date"),
    yaxis = list(title="PDM"),
    shapes = shapes
  )
p
```




```{r}
#df_merged[is.na(df_merged$pdm_trend), "pdm_trend"] <- mean(df_merged$pdm_trend, na.rm = T) 
plot_ly(df_merged[!is.na(df_merged$pdm_trend), ], x = ~date, y = ~pdm_trend, type = "scatter", mode = "lines") %>%
  layout(
    title = "PDM & Arche",
    xaxis = list(title="Date"),
    yaxis = list(title="PDM"),
    shapes = shapes
  )
```


```{r}
na_indices <- which(is.na(df_merged$pdm))
df_merged[na_indices, "pdm"] <- (df_merged[na_indices-1, "pdm"] + df_merged[na_indices+1, "pdm"])/2
```


```{r}
tmp <- decompose(ts(df_merged$pdm, frequency = 5), type = "multiplicative")
df_merged$pdm_trend <- tmp$trend
df_merged$pdm_seasonal <- tmp$seasonal
df_merged$pdm_random <- tmp$random
df_merged$pdm_trend
```

```{r}
write.csv(df_merged, file.path(path, "inst/analysis/df_merged.csv"))
```


